#ifndef __LIBPGN_ANNOTATION_H
#define __LIBPGN_ANNOTATION_H

typedef enum pgn_annotation_t {
    PGN_ANNOTATION_CHECKMATE = 0,
    PGN_ANNOTATION_GOOD_MOVE,
    PGN_ANNOTATION_EXCELLENT_MOVE,
    PGN_ANNOTATION_INTRESTING_MOVE,
    PGN_ANNOTATION_DUBIOUS_MOVE,
    PGN_ANNOTATION_MISTAKE,
    PGN_ANNOTATION_BLUNDER,
} pgn_annotation_t;

#endif // __LIBPGN_ANNOTATION_H
